spring:
  application:
    name: ayuntaweb

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/ayuntaweb
    username: ayuntaweb
    password: ayuntaweb_dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org.springframework.security: DEBUG
    com.ayuntaweb: DEBUG