spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ayuntaweb
    username: ayuntaweb
    password: ayuntaweb_dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.springframework.security: DEBUG
    com.ayuntaweb: DEBUG